name = "flo-aide"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[vars]
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
GMAIL_USER = ""
GMAIL_APP_PASSWORD = ""

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
