// @ts-expect-error: generated by opennextjs-cloudflare build
import nextWorker from "../.open-next/worker.js";

interface Env {
  NEXT_PUBLIC_SUPABASE_URL: string;
  NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
}

export default {
  ...nextWorker,
  async scheduled(_event: ScheduledEvent, env: Env, _ctx: ExecutionContext) {
    await fetch(
      `${env.NEXT_PUBLIC_SUPABASE_URL}/rest/v1/companies?select=id&limit=1`,
      {
        headers: {
          apikey: env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
          Authorization: `Bearer ${env.NEXT_PUBLIC_SUPABASE_ANON_KEY}`,
        },
      }
    );
  },
};
